{
 "title": "OFH Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gnb_id",
    "label": "gNB ID",
    "query": {
     "query": "SELECT gnb_id FROM cell GROUP BY gnb_id"
    }
   },
   {
    "name": "pci",
    "query": {
     "query": "SELECT pci FROM ofh GROUP BY pci"
    }
   }
  ]
 },
 "panels": [
  { "title": "Downlink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DL Transmitter Stats $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_transmitter_stats_late_dl_slots AS late_dl_slots, dl_transmitter_stats_late_ul_slot_requests AS late_ul_slot_requests, dl_transmitter_stats_late_cp_dl_messages AS late_cp_dl_messages, dl_transmitter_stats_late_up_dl_messages AS late_up_dl_messages, dl_transmitter_stats_late_cp_ul_messages AS late_cp_ul_messages, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  },
  {
   "title": "Ethernet Throughput $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_ethernet_transmitter_average_throughput_mbps AS dl_avg_throughput_mbps, ul_ethernet_receiver_average_throughput_mbps AS ul_avg_throughput_mbps, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  },
  {
   "title": "DL Message Encoder Latency & CPU $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_message_encoder_dl_cp_average_latency_us AS dl_cp_avg_latency_us, dl_message_encoder_dl_cp_max_latency_us AS dl_cp_max_latency_us, dl_message_encoder_dl_up_average_latency_us AS dl_up_avg_latency_us, dl_message_encoder_dl_up_max_latency_us AS dl_up_max_latency_us, dl_message_encoder_ul_cp_average_latency_us AS ul_cp_avg_latency_us, dl_message_encoder_ul_cp_max_latency_us AS ul_cp_max_latency_us, dl_message_encoder_dl_cp_cpu_usage_percent AS dl_cp_cpu_usage_percent, dl_message_encoder_dl_up_cpu_usage_percent AS dl_up_cpu_usage_percent, dl_message_encoder_ul_cp_cpu_usage_percent AS ul_cp_cpu_usage_percent, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  },
  {
   "title": "DL Message Transmitter $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT dl_message_transmitter_average_latency_us AS avg_latency_us, dl_message_transmitter_max_latency_us AS max_latency_us, dl_message_transmitter_cpu_usage_percent AS cpu_usage_percent, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  },
  { "title": "Uplink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "UL Packets & Timing $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ul_received_packets_total AS total, ul_received_packets_early AS early, ul_received_packets_on_time AS on_time, ul_received_packets_late AS late, ul_rx_window_stats_nof_missed_prach_occasions AS missed_prach, ul_rx_window_stats_nof_missed_uplink_symbols AS missed_uplink, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  },
  {
   "title": "UL Message Decoder Stats $pci",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "repeat": "pci",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT ul_message_decoder_data_average_latency_us AS data_avg_latency_us, ul_message_decoder_data_max_latency_us AS data_max_latency_us, ul_message_decoder_prach_average_latency_us AS prach_avg_latency_us, ul_message_decoder_prach_max_latency_us AS prach_max_latency_us, ul_message_decoder_data_cpu_usage_percent AS data_cpu_usage_percent, ul_message_decoder_prach_cpu_usage_percent AS prach_cpu_usage_percent, ul_message_decoder_data_nof_dropped_messages AS data_nof_dropped_messages, ul_message_decoder_prach_nof_dropped_messages AS prach_nof_dropped_messages, ul_message_decoder_ecpri_nof_future_seqid_messages AS ecpri_nof_future_seqid_messages, ul_message_decoder_ecpri_nof_past_seqid_messages AS ecpri_nof_past_seqid_messages, time FROM ofh WHERE pci == $pci AND time >= $__timeFrom AND time <= $__timeTo AND \"gnb_id\" = '$gnb_id' ORDER BY time"
    }
   ]
  }
 ]
}