#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

include:
  - local: .gitlab/ci-shared/docker.yml

stages:
  - publish

build-and-publish:
  extends: .docker-builder
  stage: publish
  rules:
    - if: $ON_MR
  variables:
    NAME: doxygen
    CONTEXT: .gitlab/ci/doxygen
    VERSION: "1.9.8-1.2023.7"
    BUILD_ARGS: DOXYGEN_VERSION=Release_1_9_8;PLANTUML_VERSION=1.2023.7
    MODE: publish
